mkdir "%ProgramFiles%\greenclone"
copy bin\Release\*.exe "%ProgramFiles%\greenclone"
copy bin\Release\*.dll "%ProgramFiles%\greenclone"
copy thirdparty\* "%ProgramFiles%\greenclone"
copy README.md "%ProgramFiles%\greenclone\README.txt"
copy INSTALL.txt "%ProgramFiles%\greenclone""